#                       #
#        WolfSpawn      #
#         config        #
#                       #
#
# Permissions
# WolfSpawn.release
# WolfSpawn.respawn
# WolfSpawn.spawn

## Options ##
# min 0 max 20
wolf-spawn-health: 5


## Messages ##
# Enable sending any messages to players on events
msg-send: true

#Specific messages
msg-death: true
msg-wolf-release: true
msg-release-toggle: true

#Message text
msg-wolf-release-text: '[WolfSpawn] You released your wolf'
msg-death-text: '[WolfSpawn] Your wolf ran home'
msg-release-toggle-on-text: "[WolfSpawn] Release enabled - your wolves won't respawn"
msg-release-toggle-off-text: '[WolfSpawn] Release disabled - your wolves will respawn again'
