name: WolfSpawn
main: com.jynxdaddy.wolfspawn.WolfSpawn
version: 0.1
commands:
  putdown:
    description: Enables player to disable respawn for his wolves.
    usage: "Usage: '/putdown' to stop your wolves respawning."