name: WolfSpawn
main: com.jynxdaddy.wolfspawn.WolfSpawn
version: 0.4.1
commands:
  releasewolf:
    description: Enables player to disable respawn for his wolves.
    usage: "Usage: '/releasewolf' to stop your wolves respawning."
  spawnwolf:
    description: Spawn a wolf for a player
    usage: "Usage: '/spawnwolf notch' to spawn notch a wolf"
    
